import { Sparkles } from 'lucide-react';
import type { Summary, Video } from '../../types';

interface AISummaryPanelProps {
  summary: Summary;
  video: Video;
  formatTimestamp: (ms: number) => string;
}

export function AISummaryPanel({ summary, video, formatTimestamp }: AISummaryPanelProps) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-4">
      <h3 className="font-semibold text-gray-900 flex items-center gap-2 mb-3">
        <Sparkles className="w-4 h-4 text-purple-600" />
        AI Summary
      </h3>
      <div className="space-y-3">
        <p className="text-sm text-gray-700 leading-relaxed">{summary.overallSummary}</p>

        {summary.keyPoints.length > 0 && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase mb-1">Key Points</h4>
            <ul className="space-y-1">
              {summary.keyPoints.map((point, idx) => (
                <li key={idx} className="text-sm text-gray-700 flex items-start gap-1.5">
                  <span className="text-purple-400 mt-0.5 flex-shrink-0">&#8226;</span>
                  {point}
                </li>
              ))}
            </ul>
          </div>
        )}

        {summary.highlights.length > 0 && (
          <div>
            <h4 className="text-xs font-semibold text-gray-500 uppercase mb-1">Highlights</h4>
            <div className="space-y-2">
              {summary.highlights.map((highlight, idx) => (
                <div key={idx} className="text-sm">
                  <button
                    onClick={() => window.open(`${video.url}&t=${Math.floor(highlight.startMs / 1000)}s`, '_blank')}
                    className="text-xs font-medium text-blue-600 hover:underline"
                  >
                    {formatTimestamp(highlight.startMs)}
                  </button>
                  <p className="text-gray-700">{highlight.summary}</p>
                  <p className="text-xs text-gray-500 italic">"{highlight.text}"</p>
                </div>
              ))}
            </div>
          </div>
        )}

        <p className="text-xs text-gray-400 pt-1 border-t border-gray-100">
          Generated by {summary.provider}/{summary.model}
        </p>
      </div>
    </div>
  );
}
